services:
  nginx: 
    build: ./requirements/nginx
    image: nginx
    container_name: nginx 
    ports:
      - "443:443"
    volumes:
      - wordpress_vm:/var/www/html
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_vm:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "sh", "-c", "ls /var/lib/mysql/${NAME_DB} && mysqladmin ping -u root -p${ROOT_PASSWD_DB}" ]
      interval: 5s
      timeout: 2s
      retries: 5
    env_file: .env
    restart: always
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_vm:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD", "ls", "/var/run/php/php8.2-fpm.pid"]
      interval: 5s
      timeout: 1s
      retries: 5
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    restart: always

volumes:
  mariadb_vm:
    driver: local
    driver_opts:
      device: "/home/daortega/data/mysql"
      o: bind
      type: none
  wordpress_vm:
    driver: local
    driver_opts:
      device: "/home/daortega/data/wordpress"
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge
